import ProjectManager from './project-manager';
import Project from './project';
import Todo from './todo';
let pm = new ProjectManager();
// let proj1 = new Project('To do list');
// console.log(pm, proj1);
// pm.addProject(proj1);
// let todo1 = new Todo();
// pm.addTodo(todo1);
export default pm;
